rules:
    disabled: [testing/tests-folder, code-quality/mypy/no-issues, code-quality/pylint/no-issues, code-quality/bandit/no-issues]
    custom: []
git:
    maxFileSize: 100000000
code-quality:
    linters:
        - pylint
        - mypy
        - black
        - isort
        - bandit
testing:
    report: "tests-report.xml"
    coverage:
        report: "coverage.xml"
