rules:
    disabled: []
    custom: []
git:
    maxFileSize: 100000000
code-quality:
    linters:
        - pylint
        - mypy
        - black
        - isort
        - bandit
testing:
    report: "tests-report.xml"
    coverage:
        report: "coverage.xml"
