stages:
  process:
    cmd: python ./src/data/make_dataset.py ./data/raw/a1_RestaurantReviews_HistoricDump.tsv ./data/processed/processed_data.joblib
    deps:
    - ./src/data/make_dataset.py
    - ./data/raw/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - ./data/processed/processed_data.joblib
  train-nb:
    cmd: | 
      python ./src/models/train_model.py ./data/raw/a1_RestaurantReviews_HistoricDump.tsv ./data/processed/processed_data.joblib ./models/sentiment_model.joblib 15
    deps:
    - ./src/models/train_model.py
    - ./data/processed/processed_data.joblib
    - ./data/raw/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - ./models/sentiment_model.joblib
    metrics:
      - naive-bayes.json:
          cache: false
  train-random-forest:
    cmd: | 
      python ./src/models/train_random_forest.py ./data/raw/a1_RestaurantReviews_HistoricDump.tsv ./data/processed/processed_data.joblib ./models/random_forest_model.joblib 12
    deps:
    - ./src/models/train_random_forest.py
    - ./data/processed/processed_data.joblib
    - ./data/raw/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - ./models/random_forest_model.joblib
    metrics:
      - random-forest.json:
          cache: false
  train-roberta:
    cmd: | 
      python ./src/models/train_twt_roberta_model.py ./models/twt_roberta_model.pkl
    deps:
    - ./src/models/train_twt_roberta_model.py
    outs:
    - ./models/twt_roberta_model.pkl
    metrics:
      - roberta.json:
          cache: false
