name: Analyze Code
run-name: Analyze Code by @${{ github.actor }}
on:
  push:
    branch: '*'
jobs:
  analyze-code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set Python Version to 3.8
        with:
          python-version: '3.8' 
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run code analysis
        run: mllint run
      - name: dvc commands
        run: |
          dvc remote list
      - name: Fetch dvc files
        run: dvc pull
      - name: Run pipeline
        run: dvc repro
      - name: Run tests
        run: pytest