name: Analyze Code
run-name: Analyze Code by @${{ github.actor }}
on:
  push:
    branch: '*'
jobs:
  analyze-code:
    runs-on: self-hosted
    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set Python Version to 3.8
        with:
          python-version: '3.8' 
      # - name: Run code analysis
      #   run: mllint run
      - name: echo dvc version
        run: dvc version
      - name: dvc commands
        run: |
          dvc remote list 
      - name: Fetch dvc files
        run: dvc pull
      - name: Run pipeline
        run: dvc repro
      - name: Run tests
        run: pytest