name: Analyze Code
run-name: Analyze Code by @${{ github.actor }}
on:
  push:
    branch: '*'
jobs:
  analyze-code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set Python Version to 3.8
        with:
          python-version: '3.8' 
      - name: Run code analysis
        run: |
          pip install -r requirements.txt
          mllint run
      - name: Exit
        run: echo "Done"