name: Build And Push Model-Training Image
run-name: Build And Push Model-Training Image by @${{ github.actor }}
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  job_1:
    name: Build & Push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $.lowercase --password-stdin
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV
          echo "old_version=${MAJOR}.${MINOR}.$(( ${PATCH} - 1 ))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - id: make_repository_name_lowercase
        name: Make Repository Name Lowercase
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: Build and Push Docker Image
        run: |
          IMG=ghcr.io/${{steps.make_repository_name_lowercase.outputs.lowercase}}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG